// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    aws_project_region: 'us-east-1',
    aws_cognito_identity_pool_id: 'us-east-1:396ef862-a164-4fce-b2aa-20a308ba96a8',
    aws_cognito_region: 'us-east-1',
    aws_user_pools_id: 'us-east-1_3YDcp0bMP',
    aws_user_pools_web_client_id: '3km5mmfmeflo7s0hlsjq93c1u0',
    oauth: {},
    aws_appsync_graphqlEndpoint: 'https://m3f5pxobunbnnivrqf4xmzjzdi.appsync-api.us-east-1.amazonaws.com/graphql',
    aws_appsync_region: 'us-east-1',
    aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS'
};


export default awsmobile;
